pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }

    tools {
        jdk 'jdk-17' // Replace with the exact name from your Jenkins config
    }

    environment {
        MAVEN_HOME = 'C:\\apache-maven-3.9.9'
    }

    stages {
        stage('Build') {
            steps {
                bat "\"%MAVEN_HOME%\\bin\\mvn\" -B -DskipTests clean package"
            }
        }

        stage('Test') {
            steps {
                bat "\"%MAVEN_HOME%\\bin\\mvn\" test"
            }
            post {
                always {
                    junit 'target\\surefire-reports\\*.xml' // Use Windows path separators
                }
            }
        }

        stage('Deliver') {
            steps {
                // Assumes you have a Windows-compatible script in the repo
                bat "call jenkins\\scripts\\deliver.bat"
            }
        }
    }
}
